title: Un cuento por semana
email: uncuentoporsemana@gmail.com
description: Fantasía, infantil, horror y todo lo demás.
author: Martín Gabriel Ríos & Ariel Gerardo Ríos
url: "http://ariel17.com.ar"
baseurl: "/uncuentoporsemana"
timezone: America/Argentina/Buenos_Aires

# Social Profiles
twitter_username: uncuentoporsemana
github_username: ariel17/uncuentoporsemana
facebook_username: uncuentoporsemana

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
