title: Un cuento por semana
email: uncuentoporsemana@gmail.com
description: Fantasía, infantil, horror y todo lo demás.
author: Martín Gabriel Ríos & Ariel Gerardo Ríos
url: "http://localhost:4000"
baseurl: ""
timezone: America/Argentina/Buenos_Aires
background: /assets/index/bg.jpg

# Google Analytics
ga:

# Social Profiles
twitter_username: 1cuentoxsemana
github_username: ariel17/uncuentoporsemana
facebook_username: uncuentoporsemana
spotify_playlist: 4cdqPrHNp4t9Q0lQW3LUzF

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

subscription_url: https://mailchi.mp/61b591e19246/uncuentoporsemana
